export const languages = [
  { value: "BG", label: "Bulgarian" },
  { value: "CS", label: "Czech" },
  { value: "DA", label: "Danish" },
  { value: "DE", label: "German" },
  { value: "EL", label: "Greek" },
  { value: "ES", label: "Spanish" },
  { value: "ET", label: "Estonian" },
  { value: "FI", label: "Finnish" },
  { value: "FR", label: "French" },
  { value: "HU", label: "Hungarian" },
  { value: "IT", label: "Italian" },
  { value: "JA", label: "Japanese" },
  { value: "LT", label: "Lithuanian" },
  { value: "LV", label: "Latvian" },
  { value: "NL", label: "Dutch" },
  { value: "PL", label: "Polish" },
  { value: "PT", label: "Portuguese" },
  { value: "RO", label: "Romanian" },
  { value: "RU", label: "Russian" },
  { value: "SK", label: "Slovak" },
  { value: "SL", label: "Slovenian" },
  { value: "SV", label: "Swedish" },
  { value: "ZH", label: "Chinese" },
];
